### ISSUE TITLE
cannot include postgres_fdw.h file.

### ISSUE THREAD

**Issue by onuraltun** [danolivo/pg_repeater#1]
i installed  postgresql 12 with enterprisedb on windows. and trying to compile with visual studio 2019. i included C:\Program Files\PostgreSQL\12\include path. but this file is not there

https://github.com/danolivo/pg_repeater/blob/93cabed0ce5cec20d36d1cd56e200a4a0091d55d/pg_repeater.c#L27

**Comment by onuraltun** [comment]
i cloned the postgres repo. and included postgres\contrib\postgres_fdw path but compiler says "LNK2019 unresolved external symbol PQexec referenced in function HOOK_ExecStart_injection"

same messages to PQClear, GetConnection, set_portable_output, b64_len...

**Comment by danolivo** [comment]
It is old project dedicated to parallel query execution on clusters.
Now this sketch converted to the "Shardman" project (Internal project of PostgresPro company)
I do not support this repository anymore.

**Comment by onuraltun** [comment]
ok, thank you
